baseurl = "https://darkestfloyd.github.io"
title = "darkestfloyd"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yourdiscussshortname"
googleAnalytics = "UA-139690492-1"

[params]
    author = "Nischal Mahaveer Chand"
    description = "my site"
    keywords = "blog,developer,personal"
    info = "Aspiring Data Scientist"
    avatarurl = "images/me.png"
    # footercontent = "darkestfloyd"

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = true

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 2
    url = "http://github.com/darkestfloyd/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 1
    url = "https://www.linkedin.com/in/nischalmc/"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 3
    url = "https://medium.com/@darkestfloyd"
[[params.social]]
    name = "StackOverflow"
    icon = "fab fa-stack-overflow"
    weight = 4
    url = "https://twitter.com/DarkestFloyd"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 5
    url = "https://twitter.com/DarkestFloyd"


[languages]
    [languages.en]
        languagename = "English"

        [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Posts"
        weight = 2
        url = "/posts/"

        [[languages.en.menu.main]]
        name = "Projects"
        weight = 3
        url = "/projects/"

        [[languages.en.menu.main]]
        name = "Resume"
        weight = 4
        url = "files/resume.pdf"
